### Updates an existing patient entity
PUT http://localhost:4000/patients/3533edb3-7a06-4a38-88a5-f90638da3e11
Content-Type: application/json

{
  "name": "Владимир Апдейтед",
  "email": "terehov_updated@gmail.com",
  "address": "Анапское шоссе 11",
  "dateOfBirth": "1975-10-20",
  "registeredDate": "2025-03-12"
}
###